-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
--vim.api.nvim_create_autocmd("ColorScheme", {
--  pattern = "*",
--  callback = function()
--    -- Forces the Treesitter markdown group to use a visual strikethrough line
--    vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
--  end,
--})
